# Name: Header
# Description: An HTTPLoadBalancer which shows how a Condition on a route routes requests with specific headers. 
# - GET projectcontour.io/ --> webapp-others.projectcontour-examples:80 
# - GET -H 'Content-Language: en' projectcontour.io/ --> webapp-en.projectcontour-examples:8080


apiVersion: projectcontour.io/v1alpha1
kind: HTTPLoadBalancer
typemeta:
  kind: ""
  apiversion: ""
objectmeta:
  name: ""
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  initializers: null
  finalizers: []
  clustername: ""
  managedfields: []
spec:
  virtualhost:
    fqdn: projectcontour.io
    tls: null
  routes:
  - condition:
      prefix: ""
      headersmatch:
        Content-Language:
        - en
      headerscontain: {}
    services:
    - name: webapp-en
      port: 80
      weight: 0
      healthcheck: null
      strategy: ""
      upstreamvalidation: null
    enablewebsockets: false
    permitinsecure: false
    prefixrewrite: ""
    timeoutpolicy: null
    retrypolicy: null
  - condition:
      prefix: /
      headersmatch: {}
      headerscontain: {}
    services:
    - name: webapp-others
      port: 80
      weight: 0
      healthcheck: null
      strategy: ""
      upstreamvalidation: null
    enablewebsockets: false
    permitinsecure: false
    prefixrewrite: ""
    timeoutpolicy: null
    retrypolicy: null
  tcpproxy: null
  includes: []
status:
  currentstatus: ""
  description: ""
---
