# Name: Delegation
# Description: A simple HTTPLoadBalancer which shows how an Include passes down a path prefix to children HTTPLoadBalancers. 
# - GET projectcontour.io/ --> webapp.default:80 
# - GET projectcontour.io/blog --> servea.teama:8080

apiVersion: projectcontour.io/v1alpha1
kind: HTTPLoadBalancer
metadata:
  name: delegate-http-loadbalancer
  namespace: default
spec:
  virtualhost:
    fqdn: kuard.local
  routes:
  - services:
    - name: kuard
      port: 80
  includes:
  - name: wwwsite
    namespace: teama
    conditions:
      prefix: /blog
---
apiVersion: projectcontour.io/v1alpha1
kind: HTTPLoadBalancer
metadata:
  name: wwwsite
  namespace: teama
spec:
  routes:
  - services:
    - name: nginx
      port: 80
---
