# Name: Delegation
# Description: A simple HTTPLoadBalancer which shows how an Include passes down a path prefix to children HTTPLoadBalancers. 
# - GET projectcontour.io/ --> webapp.projectcontour-examples:80 
# - GET projectcontour.io/blog --> servea.teama:8080

apiVersion: projectcontour.io/v1alpha1
kind: HTTPLoadBalancer
metadata:
  name: DelegateHTTPLoadBalancer
  namespace: projectcontour-examples
spec:
  virtualhost:
    fqdn: projectcontour.io
  routes:
  - services:
    - name: webapp
      port: 80
  includes:
  - name: wwwsite
    namespace: teama
    conditions:
    - prefix: /blog
---
apiVersion: projectcontour.io/v1alpha1
kind: HTTPLoadBalancer
metadata:
  name: wwwsite
  namespace: teama
spec:
  routes:
  - services:
    - name: servea
      port: 8080
---
