# Name: Delegation
# Description: An HTTPLoadBalancer which shows how an Include passes down a path prefix to children HTTPLoadBalancers as well as routes define Conditions as well. 
# - GET projectcontour.io/ --> webapp.projectcontour-examples:80 
# - GET -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36' projectcontour.io/blog/engineering --> serve-mobile.teama:8080
# - GET -H projectcontour.io/blog/engineering --> serve-www.teama:8080

apiVersion: projectcontour.io/v1alpha1
kind: HTTPLoadBalancer
typemeta:
  kind: ""
  apiversion: ""
objectmeta:
  name: ""
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  initializers: null
  finalizers: []
  clustername: ""
  managedfields: []
spec:
  virtualhost:
    fqdn: projectcontour.io
    tls: null
  routes:
  - condition: null
    services:
    - name: webapp
      port: 80
      weight: 0
      healthcheck: null
      strategy: ""
      upstreamvalidation: null
    enablewebsockets: false
    permitinsecure: false
    prefixrewrite: ""
    timeoutpolicy: null
    retrypolicy: null
  tcpproxy: null
  includes:
  - name: wwwsite
    namespace: teama
    condition:
      prefix: /blog
      headersmatch: {}
      headerscontain: {}
status:
  currentstatus: ""
  description: ""
---
apiVersion: projectcontour.io/v1alpha1
kind: HTTPLoadBalancer
typemeta:
  kind: ""
  apiversion: ""
objectmeta:
  name: ""
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  initializers: null
  finalizers: []
  clustername: ""
  managedfields: []
spec:
  virtualhost: null
  routes:
  - condition:
      prefix: /engineering
      headersmatch: {}
      headerscontain:
        user-agent:
        - Android
        - iPhone
    services:
    - name: serve-mobile
      port: 8080
      weight: 0
      healthcheck: null
      strategy: ""
      upstreamvalidation: null
    enablewebsockets: false
    permitinsecure: false
    prefixrewrite: ""
    timeoutpolicy: null
    retrypolicy: null
  - condition:
      prefix: /engineering
      headersmatch: {}
      headerscontain: {}
    services:
    - name: serve-www
      port: 8080
      weight: 0
      healthcheck: null
      strategy: ""
      upstreamvalidation: null
    enablewebsockets: false
    permitinsecure: false
    prefixrewrite: ""
    timeoutpolicy: null
    retrypolicy: null
  tcpproxy: null
  includes: []
status:
  currentstatus: ""
  description: ""
---
