# Name: Delegation
# Description: A simple IngressRoute which shows how an Include passes down a path prefix to children IngressRoutes. 
# - GET projectcontour.io/ --> webapp.projectcontour-exmaples:80 
# - GET projectcontour.io/blog --> servea.teama:8080

apiVersion: projectcontour.io/v1
kind: IngressRoute
metadata:
  name: DelegateIngressRoute
  namespace: projectcontour-examples
spec:
  virtualhost:
    fqdn: projectcontour.io
  routes:
  - match: /
    services:
    - name: webapp
      port: 80
  includes:
  - name: wwwsite
    namespace: teama
    conditions:
    - prefix: /blog
---
apiVersion: projectcontour.io/v1
kind: IngressRoute
metadata:
  name: wwwsite
  namespace: teama
spec:
  routes:
  - match: /
    services:
    - name: servea
      port: 8080
---
