# Name: Basic HTTPLoadBalancer
# Description: A basic HTTPLoadBalancer which routes a request to `projectcontour.io/` to the backend `webapp` in the namespace `projectcontour-examples`
# - GET projectcontour.io/ --> webapp.projectcontour-examples:80

apiVersion: projectcontour.io/v1alpha1
kind: HTTPLoadBalancer
typemeta:
  kind: ""
  apiversion: ""
objectmeta:
  name: ""
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  initializers: null
  finalizers: []
  clustername: ""
  managedfields: []
spec:
  virtualhost:
    fqdn: kuard.local
    tls: null
  routes:
  - condition: null
    services:
    - name: kuard
      port: 80
      weight: 0
      healthcheck: null
      strategy: ""
      upstreamvalidation: null
    enablewebsockets: false
    permitinsecure: false
    prefixrewrite: ""
    timeoutpolicy: null
    retrypolicy: null
  tcpproxy: null
  includes: []
status:
  currentstatus: ""
  description: ""
---
