# Name: Basic HTTPLoadBalancer
# Description: A basic HTTPLoadBalancer which routes a request to `projectcontour.io/` to the backend `webapp` in the namespace `projectcontour-examples`
# - GET projectcontour.io/ --> webapp.projectcontour-examples:80

apiVersion: projectcontour.io/v1alpha1
kind: HTTPLoadBalancer
metadata:
  name: basic-httploadbalancer
  namespace: default
spec:
  virtualhost:
    fqdn: kuard.local
  routes:
  - services:
    - name: kuard
      port: 80
---
